version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Change this if your requirements file is in a subdirectory
    schedule:
      interval: "daily" # Options: daily, weekly, monthly
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "" # Ignore updates for specific packages if necessary
